apiVersion: apps/v1
kind: Deployment
metadata:
  name: authployment
  labels:
    team: yarismadevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - image: gozdesaygiliyalcin/competitionauth:v001
          name: podauth
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.25"
          ports:
            - containerPort: 9090
          env:
            - name: SERVERPORT
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: auth_port
            - name: DBUSERNAME
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: db_username
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: db_password
            - name: DBURL
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: db_url
            - name: AUTHURL
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: auth_url
            - name: MAINURL
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: main_url
            - name: USERURL
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: user_url
            - name: CONFIGSERVER
              valueFrom:
                secretKeyRef:
                  name: competitionsecret
                  key: config_server_url
