server:
  port: 9090

spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: auth-service
  security:
    user:
      name: gozde
      password: 12345
  datasource:
    url: 'jdbc:postgresql://localhost:5432/competitionDB'
    username: 'postgres'
    password: '2211223'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/
    main: http://localhost:9092/
    user: http://localhost:9091/