server:
  port: 9091

logging:
  level:
    root: WARN
    org.gozdesy: DEBUG
    org.springframework: INFO
  file:
    name: user-service-application.log

spring:
  rabbitmq:
    port: 5672
    username: gozde
    password: 2211223Qwe
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: user-service
  redis:
    host: localhost
    port: 6379

  datasource:
    url: 'jdbc:postgresql://localhost:5432/competitionDB'
    username: 'postgres'
    password: '2211223'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

raceapplication:
  url:
    auth: http://localhost:9090/
    main: http://localhost:9092/
    user: http://localhost:9091/