server:
  port: 8888
spring:
  rabbitmq:
    port: 5672
    username: gozde
    password: 2211223Qwe
  application:
    name: config-server
  profiles:
    active: native
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    service:
      name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo